### ISSUE TITLE
Information regarding training/valid performance

### ISSUE THREAD

**Issue by yangfanliang** [dchen236/FairFace#2]
Hi! I hope you are doing well. 

I have been searching for face attribute classifier and your one is the best I have found.  I just wonder if it is possible for you to share some information regarding the dateset you used for training/validation and their corresponding performance (accuracy)?

Any related information would be much appreciated!

**Comment by dchen236** [comment]
Please read the referenced paper from GitHub, https://arxiv.org/abs/1908.04913 <https://arxiv.org/abs/1908.04913>
Regards,
Danni Chen   

UCLA SAMUELI SCHOOL OF ENGINEERING
Los Angeles, CA 90095-1600
www.samueli.ucla.edu <http://www.samueli.ucla.edu/>

**Comment by yangfanliang** [comment]
Got it, that is very helpful! I did not read the paper thoroughly enough.

**Comment by djalusic** [comment]
Hello @dchen236, have you trained the model from scratch on FairFace or did you use transfer learning?
