### ISSUE TITLE
The pretrained model is not recognized

### ISSUE THREAD

**Issue by SionHu** [dchen236/FairFace#9]
Hi there. Thanks for the great work! I followed the installation guide and tried to run `python3 predict_bbox.py --csv test_imgs.csv`, but it tells me `FileNotFoundError: [Errno 2] No such file or directory: 'fair_face_models/fairface_alldata_20191111.pt'`. 

I did download the models and put them in the fair_face_models folder as required. Is there another model I should download instead? 

Thanks!

**Comment by datduong** [comment]
Where did you download this pretrained model? I only see the model fairface_alldata_4race_20191111.pt.

**Comment by leenamx** [comment]
hi！ 
Where did you download this pretrained model 'fair_face_models/fairface_alldata_20191111.pt'?

I also want to download it.

Thank you!

**Comment by datduong** [comment]
The author changed the ".pt" file name. I found a different ".pt" file in their Google Drive and renamed the input variable in the code.

**Comment by ufousoumo** [comment]
Excuse me, may I ask you that how you get the pretrained models? I could not find the download link of the pretrained model.

**Comment by Haze211** [comment]
> 
@ufousoumo
You can find the link in the Readme of the repo. 
This is the link to the pretrained models: https://drive.google.com/drive/folders/1F_pXfbzWvG-bhCpNsRj6F_xsdjpesiFu

**Comment by TaoWangzj** [comment]
Can you update this link？This link is now invalid, thank you.
